// src/Components/ActionOrchestrator/utils/cssUtils/StyledCardStyles.js
// ═══════════════════════════════════════════════════════════
//  25 STYLED CARD DEFINITIONS
//  Dùng cho StyledCardAction / StyledCard component
// ═══════════════════════════════════════════════════════════

export const STYLED_CARD_TYPES = {
  GLASS_CARD: {
    name: "Glass Card",
    box: {
      padding: "24px 32px",
      background: "rgba(255,255,255,0.12)",
      borderRadius: "20px",
      backdropFilter: "blur(24px)",
      WebkitBackdropFilter: "blur(24px)",
      border: "1px solid rgba(255,255,255,0.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.25)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 700,
      fontSize: "28px",
      letterSpacing: "2px",
      color: "#FFFFFF",
      lineHeight: 1.3,
      textShadow: "0 2px 8px rgba(0,0,0,0.4)",
    },
  },
  NEON_GLOW: {
    name: "Neon Glow",
    box: {
      padding: "20px 40px",
      background: "rgba(0,0,0,0.85)",
      borderRadius: "16px",
      border: "1px solid rgba(0,234,255,0.5)",
      boxShadow:
        "0 0 20px rgba(0,234,255,0.3), 0 0 60px rgba(0,234,255,0.1), inset 0 0 20px rgba(0,234,255,0.05)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "28px",
      letterSpacing: "4px",
      textTransform: "uppercase",
      color: "#00EAFF",
      lineHeight: 1.2,
      textShadow:
        "0 0 10px rgba(0,234,255,0.8), 0 0 30px rgba(0,234,255,0.5), 0 0 60px rgba(0,234,255,0.3)",
    },
  },
  DARK_TECH: {
    name: "Dark Tech",
    box: {
      padding: "28px 36px",
      background:
        "linear-gradient(135deg, rgba(15,23,42,0.95), rgba(30,41,59,0.9))",
      borderRadius: "12px",
      border: "1px solid rgba(56,189,248,0.2)",
      boxShadow:
        "0 4px 24px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.05)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "16px",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 600,
      fontSize: "26px",
      letterSpacing: "1px",
      color: "#E2E8F0",
      lineHeight: 1.4,
    },
  },
  GRADIENT_CARD: {
    name: "Gradient Card",
    box: {
      padding: "28px 36px",
      background: "linear-gradient(135deg, #6366F1, #EC4899)",
      borderRadius: "20px",
      border: "none",
      boxShadow:
        "0 12px 40px rgba(99,102,241,0.4), 0 4px 12px rgba(236,72,153,0.2)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 800,
      fontSize: "28px",
      letterSpacing: "2px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.2,
      textShadow: "0 2px 12px rgba(0,0,0,0.3)",
    },
  },
  SOFT_SHADOW: {
    name: "Soft Shadow",
    box: {
      padding: "24px 32px",
      background: "rgba(255,255,255,0.95)",
      borderRadius: "16px",
      border: "none",
      boxShadow: "0 4px 20px rgba(0,0,0,0.08), 0 12px 48px rgba(0,0,0,0.06)",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: "12px",
    },
    text: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "0.5px",
      color: "#1E293B",
      lineHeight: 1.5,
    },
  },
  PREMIUM_TITLE: {
    name: "Premium Title",
    box: {
      padding: "32px 48px",
      background:
        "linear-gradient(180deg, rgba(0,0,0,0.9), rgba(20,20,20,0.85))",
      borderRadius: "4px",
      border: "2px solid rgba(212,175,55,0.5)",
      boxShadow:
        "0 8px 32px rgba(0,0,0,0.6), inset 0 1px 0 rgba(212,175,55,0.15)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "16px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "32px",
      letterSpacing: "8px",
      textTransform: "uppercase",
      color: "#D4AF37",
      lineHeight: 1.1,
      textShadow: "0 0 20px rgba(212,175,55,0.4), 0 2px 4px rgba(0,0,0,0.8)",
    },
  },
  HIGHLIGHT_TAG: {
    name: "Highlight Tag",
    box: {
      padding: "10px 24px",
      background: "linear-gradient(135deg, #10B981, #059669)",
      borderRadius: "100px",
      border: "none",
      boxShadow: "0 4px 16px rgba(16,185,129,0.35)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
    },
    text: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 800,
      fontSize: "22px",
      letterSpacing: "2px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.2,
    },
  },
  WARNING_BOX: {
    name: "Warning Box",
    box: {
      padding: "24px 36px",
      background:
        "linear-gradient(135deg, rgba(220,38,38,0.95), rgba(234,88,12,0.9))",
      borderRadius: "14px",
      border: "2px solid rgba(255,255,255,0.2)",
      boxShadow:
        "0 8px 32px rgba(220,38,38,0.4), 0 0 0 4px rgba(220,38,38,0.15)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "14px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 800,
      fontSize: "28px",
      letterSpacing: "3px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.2,
      textShadow: "0 2px 8px rgba(0,0,0,0.4)",
    },
  },
  CTA_BADGE: {
    name: "CTA Badge",
    box: {
      padding: "18px 44px",
      background: "linear-gradient(135deg, #F59E0B, #EF4444)",
      borderRadius: "100px",
      border: "3px solid rgba(255,255,255,0.3)",
      boxShadow:
        "0 8px 24px rgba(245,158,11,0.45), 0 2px 8px rgba(239,68,68,0.3)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "26px",
      letterSpacing: "4px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.1,
      textShadow: "0 2px 6px rgba(0,0,0,0.3)",
    },
  },
  STATISTIC_CARD: {
    name: "Statistic Card",
    box: {
      padding: "32px 40px",
      background:
        "linear-gradient(145deg, rgba(15,23,42,0.97), rgba(30,58,95,0.95))",
      borderRadius: "18px",
      border: "1px solid rgba(59,130,246,0.25)",
      boxShadow:
        "0 16px 48px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.05)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "52px",
      letterSpacing: "2px",
      color: "#3B82F6",
      lineHeight: 1.0,
      textShadow: "0 0 30px rgba(59,130,246,0.5)",
    },
    subText: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 600,
      fontSize: "18px",
      letterSpacing: "3px",
      textTransform: "uppercase",
      color: "rgba(148,163,184,0.9)",
      lineHeight: 1.3,
    },
  },
  EXPERT_NAME_TAG: {
    name: "Expert Name Tag",
    box: {
      padding: "20px 32px",
      background:
        "linear-gradient(90deg, rgba(0,0,0,0.9), rgba(0,0,0,0.6), transparent)",
      borderRadius: "0 12px 12px 0",
      border: "none",
      borderLeft: "4px solid #3B82F6",
      boxShadow: "0 4px 24px rgba(0,0,0,0.4)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "4px",
      flexDirection: "column",
      minWidth: "300px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "2px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.2,
    },
    subText: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 400,
      fontSize: "18px",
      letterSpacing: "1px",
      color: "rgba(148,163,184,0.9)",
      lineHeight: 1.3,
    },
  },
  QUOTE_HIGHLIGHT: {
    name: "Quote Highlight",
    box: {
      padding: "36px 44px",
      background: "rgba(0,0,0,0.75)",
      borderRadius: "24px",
      backdropFilter: "blur(20px)",
      WebkitBackdropFilter: "blur(20px)",
      border: "1px solid rgba(255,255,255,0.1)",
      borderLeft: "4px solid #F59E0B",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "8px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "0.5px",
      color: "#FFFFFF",
      lineHeight: 1.5,
      fontStyle: "italic",
    },
  },
  STEP_COUNTER: {
    name: "Step Counter",
    hasStep: true,
    box: {
      padding: "20px 36px",
      background:
        "linear-gradient(135deg, rgba(99,102,241,0.15), rgba(139,92,246,0.1))",
      borderRadius: "16px",
      backdropFilter: "blur(16px)",
      WebkitBackdropFilter: "blur(16px)",
      border: "1px solid rgba(99,102,241,0.3)",
      boxShadow: "0 4px 20px rgba(99,102,241,0.15)",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: "20px",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 600,
      fontSize: "24px",
      letterSpacing: "0.5px",
      color: "#FFFFFF",
      lineHeight: 1.4,
    },
    stepStyle: {
      width: "48px",
      height: "48px",
      background: "linear-gradient(135deg, #6366F1, #8B5CF6)",
      borderRadius: "50%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "0 4px 16px rgba(99,102,241,0.4)",
      flexShrink: 0,
    },
    stepTextStyle: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "22px",
      color: "#fff",
    },
  },
  MEDICAL_INFO: {
    name: "Medical Info",
    box: {
      padding: "28px 36px",
      background:
        "linear-gradient(135deg, rgba(6,78,59,0.95), rgba(4,120,87,0.9))",
      borderRadius: "16px",
      border: "1px solid rgba(52,211,153,0.3)",
      boxShadow:
        "0 8px 32px rgba(6,78,59,0.4), inset 0 1px 0 rgba(255,255,255,0.05)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "8px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "1px",
      color: "#ECFDF5",
      lineHeight: 1.4,
    },
    subText: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 600,
      fontSize: "18px",
      letterSpacing: "0.5px",
      color: "rgba(167,243,208,0.85)",
      lineHeight: 1.4,
    },
  },
  BOLD_IMPACT: {
    name: "Bold Impact",
    box: {
      padding: "16px 24px",
      background: "transparent",
      borderRadius: "0",
      border: "none",
      boxShadow: "none",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "48px",
      letterSpacing: "4px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.1,
      WebkitTextStroke: "2px rgba(0,0,0,0.8)",
      paintOrder: "stroke fill",
      textShadow: "0 4px 16px rgba(0,0,0,0.6), 0 8px 32px rgba(0,0,0,0.3)",
    },
  },
  MINIMAL_LABEL: {
    name: "Minimal Label",
    box: {
      padding: "8px 20px",
      background: "rgba(0,0,0,0.5)",
      borderRadius: "8px",
      backdropFilter: "blur(8px)",
      WebkitBackdropFilter: "blur(8px)",
      border: "none",
      boxShadow: "none",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 500,
      fontSize: "18px",
      letterSpacing: "1px",
      textTransform: "uppercase",
      color: "rgba(255,255,255,0.85)",
      lineHeight: 1.3,
    },
  },
  FIRE_BANNER: {
    name: "Fire Banner",
    box: {
      padding: "14px 32px",
      background: "linear-gradient(90deg, #DC2626, #F97316, #EAB308)",
      borderRadius: "8px",
      border: "none",
      boxShadow:
        "0 4px 20px rgba(220,38,38,0.5), 0 0 40px rgba(249,115,22,0.2)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
    },
    text: {
      fontFamily: "'Bangers', cursive",
      fontWeight: 400,
      fontSize: "32px",
      letterSpacing: "6px",
      textTransform: "uppercase",
      color: "#FFFFFF",
      lineHeight: 1.1,
      textShadow: "0 2px 4px rgba(0,0,0,0.4)",
    },
  },
  ICY_GLASS: {
    name: "Icy Glass",
    box: {
      padding: "24px 32px",
      background:
        "linear-gradient(135deg, rgba(59,130,246,0.15), rgba(147,197,253,0.1))",
      borderRadius: "18px",
      backdropFilter: "blur(20px)",
      WebkitBackdropFilter: "blur(20px)",
      border: "1px solid rgba(59,130,246,0.25)",
      boxShadow:
        "0 8px 32px rgba(59,130,246,0.1), inset 0 1px 0 rgba(255,255,255,0.1)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "12px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "Nunito, sans-serif",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "0.5px",
      color: "#FFFFFF",
      lineHeight: 1.4,
    },
  },
  HANDWRITTEN_ACCENT: {
    name: "Handwritten Accent",
    box: {
      padding: "16px 28px",
      background: "rgba(255,251,235,0.9)",
      borderRadius: "12px",
      border: "2px dashed rgba(217,119,6,0.4)",
      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
    },
    text: {
      fontFamily: "'Dancing Script', cursive",
      fontWeight: 700,
      fontSize: "30px",
      letterSpacing: "1px",
      color: "#92400E",
      lineHeight: 1.4,
    },
  },
  GRADIENT_TEXT_ONLY: {
    name: "Gradient Text Only",
    box: {
      padding: "0",
      background: "transparent",
      borderRadius: "0",
      border: "none",
      boxShadow: "none",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 900,
      fontSize: "40px",
      letterSpacing: "6px",
      textTransform: "uppercase",
      background: "linear-gradient(135deg, #FFFFFF, #60A5FA, #A78BFA)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      backgroundClip: "text",
      lineHeight: 1.1,
      filter: "drop-shadow(0 4px 12px rgba(96,165,250,0.4))",
    },
  },
  PHARMA_CARD: {
    name: "Pharma Card",
    box: {
      padding: "24px 32px",
      background: "linear-gradient(180deg, #FFFFFF, #F0FDFA)",
      borderRadius: "16px",
      border: "1px solid rgba(20,184,166,0.3)",
      borderTop: "4px solid #14B8A6",
      boxShadow: "0 4px 20px rgba(20,184,166,0.12), 0 1px 4px rgba(0,0,0,0.05)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "8px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 700,
      fontSize: "24px",
      letterSpacing: "1px",
      color: "#0F766E",
      lineHeight: 1.4,
    },
    subText: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 400,
      fontSize: "18px",
      letterSpacing: "0.5px",
      color: "#5B7A78",
      lineHeight: 1.5,
    },
  },
  BUBBLE_POP: {
    name: "Bubble Pop",
    box: {
      padding: "24px 36px",
      background: "linear-gradient(135deg, #FDE68A, #FBBF24)",
      borderRadius: "32px",
      border: "3px solid #F59E0B",
      boxShadow: "0 8px 24px rgba(251,191,36,0.35), 4px 4px 0 #E09100",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "10px",
    },
    text: {
      fontFamily: "'Fuzzy Bubbles', cursive",
      fontWeight: 700,
      fontSize: "26px",
      letterSpacing: "2px",
      color: "#7C2D12",
      lineHeight: 1.3,
    },
  },
  CINEMA_SUBTITLE: {
    name: "Cinema Subtitle",
    box: {
      padding: "14px 32px",
      background: "rgba(0,0,0,0.65)",
      borderRadius: "8px",
      border: "none",
      boxShadow: "0 4px 16px rgba(0,0,0,0.3)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    text: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 600,
      fontSize: "24px",
      letterSpacing: "0.5px",
      color: "#FFFFFF",
      lineHeight: 1.5,
      textShadow: "0 1px 4px rgba(0,0,0,0.5)",
    },
  },
  ELECTRIC_PURPLE: {
    name: "Electric Purple",
    box: {
      padding: "20px 40px",
      background:
        "linear-gradient(135deg, rgba(88,28,135,0.9), rgba(124,58,237,0.85))",
      borderRadius: "14px",
      border: "1px solid rgba(167,139,250,0.3)",
      boxShadow:
        "0 8px 32px rgba(124,58,237,0.35), 0 0 60px rgba(139,92,246,0.1)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 800,
      fontSize: "28px",
      letterSpacing: "3px",
      textTransform: "uppercase",
      color: "#F5F3FF",
      lineHeight: 1.2,
      textShadow: "0 0 20px rgba(167,139,250,0.6)",
    },
  },
  AUTHORITY_BANNER: {
    name: "Authority Banner",
    box: {
      padding: "20px 36px",
      background:
        "linear-gradient(90deg, rgba(15,23,42,0.97), rgba(30,41,59,0.9))",
      borderRadius: "12px",
      border: "1px solid rgba(212,175,55,0.3)",
      borderBottom: "3px solid #D4AF37",
      boxShadow: "0 8px 24px rgba(0,0,0,0.5)",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      gap: "4px",
      flexDirection: "column",
    },
    text: {
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 700,
      fontSize: "24px",
      letterSpacing: "2px",
      color: "#D4AF37",
      lineHeight: 1.3,
    },
    subText: {
      fontFamily: "'Be Vietnam Pro', sans-serif",
      fontWeight: 400,
      fontSize: "18px",
      letterSpacing: "0.5px",
      color: "#94A3B8",
      lineHeight: 1.4,
    },
  },
};

// ═══════════════════════════════════════════════════════════
//  BACKGROUND OPTIONS
// ═══════════════════════════════════════════════════════════
export const BG_OPTIONS = {
  medical: "linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #0f172a 100%)",
  nature: "linear-gradient(135deg, #134e4a 0%, #064e3b 50%, #1a2e05 100%)",
  warm: "linear-gradient(135deg, #7c2d12 0%, #9a3412 50%, #451a03 100%)",
  purple: "linear-gradient(135deg, #3b0764 0%, #581c87 50%, #1e1b4b 100%)",
  light: "linear-gradient(135deg, #e2e8f0, #f1f5f9, #e2e8f0)",
  none: "transparent",
};

// Helper: lấy style definition theo type
export function getStyledCardDef(type) {
  return STYLED_CARD_TYPES[type] || STYLED_CARD_TYPES.GLASS_CARD;
}
